// Generated by Selenium IDE
import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class AnswerTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", "C:\\Users\\user\\Downloads\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    //driver.quit();
  }
  @Test
  public void answerTest() {
    driver.get("http://localhost:8080/groupware/home");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.findElement(By.linkText("로그인")).click();
    driver.findElement(By.id("userLoginID")).sendKeys("60181111");
    driver.findElement(By.id("userLoginPW")).sendKeys("gkb13902");
    driver.findElement(By.id("userLoginPW")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("문의")).click();
    driver.findElement(By.linkText("문의")).click();
    driver.findElement(By.linkText("문의")).click();
    driver.findElement(By.linkText("문의하기")).click();
    driver.findElement(By.linkText("예약 확인 테스트")).click();
    driver.findElement(By.id("inquiryAnswer")).click();
    driver.findElement(By.id("inquiryAnswer")).sendKeys("알겠어요");
    driver.findElement(By.id("saveButton")).click();
    driver.findElement(By.linkText("예약;")).click();
    driver.findElement(By.id("listButton")).click();
  }
}
