// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InquiryTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", "C:\\Selenium\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    //driver.quit();
  }
  @Test
  public void inquiryTest() {
    driver.get("http://localhost:8080/groupware/home");
    driver.manage().window().setSize(new Dimension(1318, 866));
    driver.findElement(By.linkText("로그인")).click();
    driver.findElement(By.id("userLoginID")).click();
    driver.findElement(By.id("userLoginID")).sendKeys("12311231");
    driver.findElement(By.id("userLoginPW")).sendKeys("12311231");
    driver.findElement(By.id("userLoginPW")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("문의")).click();
    driver.findElement(By.linkText("문의")).click();
    driver.findElement(By.linkText("문의")).click();
    driver.findElement(By.linkText("문의하기")).click();
    driver.findElement(By.linkText("글쓰기")).click();
    driver.findElement(By.id("inquiryType")).click();
    
    {
      WebElement dropdown = driver.findElement(By.id("inquiryType"));
      dropdown.findElement(By.xpath("//option[. = '강의실 예약/이용']")).click();
    }
    driver.findElement(By.id("inquiryTitle")).click();
    driver.findElement(By.id("inquiryTitle")).sendKeys("예약;");
    driver.findElement(By.cssSelector(".ck-editor__editable")).click();
    driver.findElement(By.cssSelector(".ck-editor__editable")).sendKeys("테스트입니다");
    driver.findElement(By.id("saveButton")).click();
    driver.findElement(By.cssSelector(".mb-3")).click();
  }
}
