// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LectureRoomReservationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", "C:\\Selenium\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    //driver.quit();
  }
  @Test
  public void lectureRoomReservation() {
    driver.get("http://localhost:8080/groupware/home");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.findElement(By.linkText("로그인")).click();
    driver.findElement(By.id("userLoginID")).sendKeys("12311231");
    driver.findElement(By.id("userLoginPW")).sendKeys("12311231");
    driver.findElement(By.id("form")).click();
    driver.findElement(By.id("submitId")).click();
    driver.findElement(By.linkText("강의실")).click();
    driver.findElement(By.linkText("강의실")).click();
    driver.findElement(By.linkText("강의실")).click();
    driver.findElement(By.linkText("강의실 예약")).click();
    driver.findElement(By.linkText("1246")).click();
    driver.findElement(By.id("reservationStartTime")).click();
    {
      WebElement dropdown = driver.findElement(By.id("reservationStartTime"));
      dropdown.findElement(By.xpath("//option[. = '09:00~11:00']")).click();
    }
    driver.findElement(By.id("reservationNumOfPeople")).click();
    driver.findElement(By.id("reservationNumOfPeople")).sendKeys("10");
    driver.findElement(By.id("saveButton")).click();
    driver.findElement(By.linkText("강의실")).click();
    driver.findElement(By.linkText("강의실")).click();
    driver.findElement(By.linkText("강의실")).click();
    driver.findElement(By.linkText("예약 확인")).click();
  }
}
